"""
07_upload_embeddings.py
Upload pre-computed Pl@ntNet embeddings to Labelbox.

Embeddings are generated by 03b_multi_predict.py as a by-product of the
survey/tiles API call (no extra API cost). This script only handles the
Labelbox upload step.

The Labelbox embedding type is named from the Pl@ntNet model version found
in embeddings.json (e.g. "PlantNet-v7.4-2026-03"), enabling tracking across
Pl@ntNet retraining cycles.

Inputs:
  - config.yaml
  - output/embeddings/embeddings.json  (produced by 03b_multi_predict.py)
  - output/images/dataset_id.txt

Outputs:
  - output/embeddings/embeddings_summary.json
  - Embeddings uploaded to Labelbox
"""

import os
import sys
import json
import re
import time
import yaml
import labelbox as lb
from dotenv import load_dotenv
from datetime import datetime

# ─── Paths ───────────────────────────────────────────────────────
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
load_dotenv(os.path.join(PROJECT_ROOT, ".env"))

with open(os.path.join(PROJECT_ROOT, "config.yaml"), "r") as f:
    cfg = yaml.safe_load(f)

lb_cfg = cfg["labelbox"]
DATASET_ID_DIR = os.path.join(PROJECT_ROOT, cfg["folders"]["output_images"])
EMBEDDINGS_DIR = os.path.join(PROJECT_ROOT, cfg["folders"]["output_embeddings"])
EMBEDDING_DIMS = lb_cfg["embedding_dims"]

# ─── Load embeddings ─────────────────────────────────────────────
embeddings_path = os.path.join(EMBEDDINGS_DIR, "embeddings.json")
if not os.path.exists(embeddings_path):
    sys.exit(
        f"ERROR: {embeddings_path} not found.\n"
        "Run scripts/03_predictions/03b_multi_predict.py first."
    )

with open(embeddings_path, "r") as f:
    embeddings_data = json.load(f)

if not embeddings_data:
    sys.exit("ERROR: embeddings.json is empty.")

print("=" * 60)
print("STEP 1: Loading embeddings from disk")
print("=" * 60)
print(f"  Loaded {len(embeddings_data)} embeddings from {embeddings_path}")

# Extract Pl@ntNet version from first entry
plantnet_version = embeddings_data[0].get("plantnet_version", "unknown")
print(f"  Pl@ntNet version: {plantnet_version}")

# ─── Build dynamic embedding name ────────────────────────────────
# version string example: "2026-02-17 (7.4)" -> extract "7.4"
version_short = "unknown"
if plantnet_version:
    match = re.search(r"\(([^)]+)\)", plantnet_version)
    version_short = match.group(1) if match else plantnet_version.split()[0]

run_month = datetime.now().strftime("%Y-%m")
EMBEDDING_NAME = f"PlantNet-v{version_short}-{run_month}"
print(f"  Embedding name: '{EMBEDDING_NAME}'")

# ─── Connect to Labelbox ─────────────────────────────────────────
print("\n" + "=" * 60)
print("STEP 2: Uploading embeddings to Labelbox")
print("=" * 60)

LABELBOX_API_KEY = os.getenv("LABELBOX_API_KEY")
if not LABELBOX_API_KEY:
    sys.exit("ERROR: LABELBOX_API_KEY not found in .env")

client = lb.Client(api_key=LABELBOX_API_KEY)
print("  Connected to Labelbox")

# ─── Create or get embedding type ────────────────────────────────
embedding = None
try:
    embedding = client.get_embedding_by_name(EMBEDDING_NAME)
    print(f"  Found existing embedding type: {embedding.id} ({embedding.dims} dims)")
except Exception:
    print(f"  Not found. Creating new embedding type ({EMBEDDING_DIMS} dims)...")
    embedding = client.create_embedding(EMBEDDING_NAME, EMBEDDING_DIMS)
    print(f"  Created embedding type: {embedding.id}")

# ─── Load dataset ────────────────────────────────────────────────
with open(os.path.join(DATASET_ID_DIR, "dataset_id.txt")) as f:
    dataset_id = f.read().strip()

dataset = client.get_dataset(dataset_id)
print(f"  Dataset: {dataset.name}")

gk_to_dr_id = {}
for dr in dataset.data_rows():
    if dr.global_key:
        gk_to_dr_id[dr.global_key] = dr.uid
print(f"  Data rows with global keys: {len(gk_to_dr_id)}")

# ─── Build upsert payload ────────────────────────────────────────
payload = []
skipped = 0

for entry in embeddings_data:
    gk = entry["global_key"]
    if gk not in gk_to_dr_id:
        print(f"  WARNING: global_key '{gk}' not found in dataset, skipping")
        skipped += 1
        continue
    payload.append({
        "key": lb.UniqueId(gk_to_dr_id[gk]),
        "embeddings": [{
            "embedding_id": embedding.id,
            "vector": entry["embedding"],
        }],
    })

print(f"\n  Payload: {len(payload)} data row(s) to upsert ({skipped} skipped)")

if not payload:
    sys.exit("ERROR: No data rows matched. Check global_key_prefix in config.yaml.")

# ─── Upsert embeddings ───────────────────────────────────────────
print("  Uploading embeddings...")
task = dataset.upsert_data_rows(payload)
task.wait_till_done()

print(f"  Status: {task.status}")
if task.errors:
    print(f"  Errors: {task.errors[:5]}")
else:
    print("  No errors!")

# ─── Verify count ─────────────────────────────────────────────────
print("\n  Waiting 10 seconds for Labelbox to index embeddings...")
time.sleep(10)
count = embedding.get_imported_vector_count()
print(f"  Imported vector count for '{EMBEDDING_NAME}': {count}")

# ─── Summary ─────────────────────────────────────────────────────
summary = {
    "embedding_name": EMBEDDING_NAME,
    "embedding_id": embedding.id,
    "embedding_dims": EMBEDDING_DIMS,
    "model": "Pl@ntNet survey/tiles (mean-pooled tiles, L2-normalized)",
    "plantnet_version": plantnet_version,
    "images_processed": len(embeddings_data),
    "embeddings_uploaded": len(payload),
    "skipped": skipped,
    "imported_vector_count": count,
    "timestamp": datetime.now().isoformat(),
}

summary_path = os.path.join(EMBEDDINGS_DIR, "embeddings_summary.json")
with open(summary_path, "w") as f:
    json.dump(summary, f, indent=2)

print(f"""
{'=' * 60}
PL@NTNET EMBEDDINGS UPLOADED
{'=' * 60}
Model:       Pl@ntNet survey/tiles ({plantnet_version})
Pooling:     mean across tiles (L2-normalized)
Images:      {len(embeddings_data)} processed
Uploaded:    {len(payload)} embeddings
Skipped:     {skipped}
LB count:    {count} vectors indexed
Embedding:   {EMBEDDING_NAME} ({embedding.id})
Summary:     {summary_path}
{'=' * 60}

Next: Open Labelbox Catalog -> select an image -> click
      "Find similar" -> choose "{EMBEDDING_NAME}" embedding.
{'=' * 60}
""")
